In [1]:
#Import python libraries
import pandas as pd
import numpy as np
import os

In [2]:
#Read excel files
benin = pd.read_excel('developing/Benin - all projects.xlsx',engine="openpyxl")
developing_downloaded = pd.read_csv('developing/developing_downloaded_18_20.csv')
developing_scrapped = pd.read_csv('developing/developing_scrapped_18_20.csv',encoding='latin-1')
ghana = pd.read_excel('developing/Ghana - all projects.xlsx',engine="openpyxl")
ivory_coast = pd.read_excel('developing/Ivory Coast - all projects.xlsx',engine="openpyxl")
kenya_03_14 = pd.read_excel('developing/Kenya 2003 to 2014 - Projects (rows 1 to 397).xlsx',engine="openpyxl")
kenya_14_20 = pd.read_excel('developing/Kenya 2014 to 2020 - Projects (rows 1 to 319).xlsx',engine="openpyxl")
mali = pd.read_excel('developing/Mali - all projects.xlsx',engine="openpyxl")
mozambique = pd.read_excel('developing/Mozambique - all projects.xlsx',engine="openpyxl")
nigeria = pd.read_excel('developing/Nigeria - 2003 to 2013.xlsx',engine="openpyxl")
rwanda = pd.read_excel('developing/Rwanda - all projects.xlsx',engine="openpyxl")
SA_03_08 = pd.read_excel('developing/SA 2003 to 2008 - Projects (rows 1 to 462).xlsx',engine="openpyxl")
SA_09_11 = pd.read_excel('developing/SA 2009 to 2011 - Projects (rows 1 to 438).xlsx',engine="openpyxl")
SA_12_14 = pd.read_excel('developing/SA 2012 to 2014 - Projects (rows 1 to 485).xlsx',engine="openpyxl")
SA_15_17 = pd.read_excel('developing/SA 2015 to 2017 - Projects (rows 1 to 342).xlsx',engine="openpyxl")
SA_18_20 = pd.read_excel('developing/SA 2018 to 2020 - Projects (rows 1 to 287).xlsx',engine="openpyxl")
sierra_leone = pd.read_excel('developing/Sierra Leone - all projects.xlsx',engine="openpyxl")
tanzania = pd.read_excel('developing/Tanzania - all projects.xlsx',engine="openpyxl")
uganda = pd.read_excel('developing/Uganda - all projects.xlsx',engine="openpyxl")
uganda.drop(uganda.columns[0], axis=1, inplace=True)
tanzania.drop(tanzania.columns[0], axis=1, inplace=True)
SA_18_20.drop(SA_18_20.columns[0], axis=1, inplace=True)
SA_15_17.drop(SA_15_17.columns[0], axis=1, inplace=True)
SA_12_14.drop(SA_12_14.columns[0], axis=1, inplace=True)
SA_09_11.drop(SA_09_11.columns[0], axis=1, inplace=True)
SA_03_08.drop(SA_03_08.columns[0], axis=1, inplace=True)
rwanda.drop(rwanda.columns[0], axis=1, inplace=True)
nigeria.drop(nigeria.columns[0], axis=1, inplace=True)
mozambique.drop(mozambique.columns[0], axis=1, inplace=True)
mali.drop(mali.columns[0], axis=1, inplace=True)
kenya_14_20.drop(kenya_14_20.columns[0], axis=1, inplace=True)
kenya_03_14.drop(kenya_03_14.columns[0], axis=1, inplace=True)
ivory_coast.drop(ivory_coast.columns[0], axis=1, inplace=True)
ghana.drop(ghana.columns[0], axis=1, inplace=True)
developing_scrapped.drop(developing_scrapped.columns[0], axis=1, inplace=True)
developing_scrapped.drop('Unnamed0', axis=1, inplace=True)
benin = benin.dropna(subset=['#'])
benin.drop(benin.columns[0], axis=1, inplace=True)

In [19]:
kenya_14_20['email 1 '].value_counts()

tariq@bitzer.ae                     2
jim.berlin@logisticsplus.net        2
chris@slatecube.com                 1
lei.jun@xiaomi.com                  1
snehal@cloudlendinginc.com          1
vesa.korhonen@nocart.com            1
Kimacia.gitau@cisi.org              1
Irene.kaloki@ke.fracht.com          1
aaron@nest.vc                       1
marina.stenfors@vaisala.com         1
mark.plungy@varian.com              1
wesley@snapplify.com                1
zaren.ramlugan@za.syspro.com        1
christoph.thuenemann@bericap.com    1
angela.munyua@vivoenergy.com        1
Name: email 1 , dtype: int64

In [3]:
#make all columns lower case
benin.columns = benin.columns.str.lower()
developing_downloaded.columns = developing_downloaded.columns.str.lower()
developing_scrapped.columns = developing_scrapped.columns.str.lower()
ghana.columns = ghana.columns.str.lower()
ivory_coast.columns = ivory_coast.columns.str.lower()
kenya_03_14.columns = kenya_03_14.columns.str.lower()
kenya_14_20.columns = kenya_14_20.columns.str.lower()
mali.columns = mali.columns.str.lower()
mozambique.columns = mozambique.columns.str.lower()
nigeria.columns = nigeria.columns.str.lower()
rwanda.columns = rwanda.columns.str.lower()
SA_03_08.columns = SA_03_08.columns.str.lower()
SA_09_11.columns = SA_09_11.columns.str.lower()
SA_12_14.columns = SA_12_14.columns.str.lower()
SA_15_17.columns = SA_15_17.columns.str.lower()
SA_18_20.columns = SA_18_20.columns.str.lower()
sierra_leone.columns = sierra_leone.columns.str.lower()
tanzania.columns = tanzania.columns.str.lower()
uganda.columns = uganda.columns.str.lower()

In [4]:
#keep alphabets and numbers in columns
benin.columns = benin.columns.str.replace('[^a-zA-Z0-9]', ' ')
developing_downloaded.columns = developing_downloaded.columns.str.replace('[^a-zA-Z0-9]', ' ')
developing_scrapped.columns = developing_scrapped.columns.str.replace('[^a-zA-Z0-9]', ' ')
ghana.columns = ghana.columns.str.replace('[^a-zA-Z0-9]', ' ')
ivory_coast.columns = ivory_coast.columns.str.replace('[^a-zA-Z0-9]', ' ')
kenya_03_14.columns = kenya_03_14.columns.str.replace('[^a-zA-Z0-9]', ' ')
kenya_14_20.columns = kenya_14_20.columns.str.replace('[^a-zA-Z0-9]', ' ')
mali.columns = mali.columns.str.replace('[^a-zA-Z0-9]', ' ')
mozambique.columns = mozambique.columns.str.replace('[^a-zA-Z0-9]', ' ')
nigeria.columns = nigeria.columns.str.replace('[^a-zA-Z0-9]', ' ')
rwanda.columns = rwanda.columns.str.replace('[^a-zA-Z0-9]', ' ')
SA_03_08.columns = SA_03_08.columns.str.replace('[^a-zA-Z0-9]', ' ')
SA_09_11.columns = SA_09_11.columns.str.replace('[^a-zA-Z0-9]', ' ')
SA_12_14.columns = SA_12_14.columns.str.replace('[^a-zA-Z0-9]', ' ')
SA_15_17.columns = SA_15_17.columns.str.replace('[^a-zA-Z0-9]', ' ')
SA_18_20.columns = SA_18_20.columns.str.replace('[^a-zA-Z0-9]', ' ')
sierra_leone.columns = sierra_leone.columns.str.replace('[^a-zA-Z0-9]', ' ')
tanzania.columns = tanzania.columns.str.replace('[^a-zA-Z0-9]', ' ')
uganda.columns = uganda.columns.str.replace('[^a-zA-Z0-9]', ' ')

In [5]:
#Remove extra space from column names
benin.columns = benin.columns.str.replace(r'\s+', ' ', regex=True)
developing_downloaded.columns = developing_downloaded.columns.str.replace(r'\s+', ' ', regex=True)
developing_scrapped.columns = developing_scrapped.columns.str.replace(r'\s+', ' ', regex=True)
ghana.columns = ghana.columns.str.replace(r'\s+', ' ', regex=True)
ivory_coast.columns = ivory_coast.columns.str.replace(r'\s+', ' ', regex=True)
kenya_03_14.columns = kenya_03_14.columns.str.replace(r'\s+', ' ', regex=True)
kenya_14_20.columns = kenya_14_20.columns.str.replace(r'\s+', ' ', regex=True)
mali.columns = mali.columns.str.replace(r'\s+', ' ', regex=True)
mozambique.columns = mozambique.columns.str.replace(r'\s+', ' ', regex=True)
nigeria.columns = nigeria.columns.str.replace(r'\s+', ' ', regex=True)
rwanda.columns = rwanda.columns.str.replace(r'\s+', ' ', regex=True)
SA_03_08.columns = SA_03_08.columns.str.replace(r'\s+', ' ', regex=True)
SA_09_11.columns = SA_09_11.columns.str.replace(r'\s+', ' ', regex=True)
SA_12_14.columns = SA_12_14.columns.str.replace(r'\s+', ' ', regex=True)
SA_15_17.columns = SA_15_17.columns.str.replace(r'\s+', ' ', regex=True)
SA_18_20.columns = SA_18_20.columns.str.replace(r'\s+', ' ', regex=True)
sierra_leone.columns = sierra_leone.columns.str.replace(r'\s+', ' ', regex=True)
tanzania.columns = tanzania.columns.str.replace(r'\s+', ' ', regex=True)
uganda.columns = uganda.columns.str.replace(r'\s+', ' ', regex=True)

In [6]:
# Rename column "source admin region us county " to "source admin region" , "destination admin region us county " to "destination admin region", "date" to "project date" in all dataframes
benin.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
developing_downloaded.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
developing_scrapped.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
ghana.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
ivory_coast.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
kenya_03_14.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
kenya_14_20.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
mali.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
mozambique.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
nigeria.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
rwanda.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
SA_03_08.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
SA_09_11.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
SA_12_14.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
SA_15_17.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
SA_18_20.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
sierra_leone.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
tanzania.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)
uganda.rename(columns={'source admin region us county ': 'source admin region', 'destination admin region us county ': 'destination admin region', 'date': 'project date'}, inplace=True)

Rename wherever necessary

In [7]:
developing_downloaded.rename(columns={'sub sector':'sub sector'}, inplace=True)
developing_scrapped.rename(columns={'subsector':'sub sector'}, inplace=True)
developing_scrapped.rename(columns={'freezone':'free zone'}, inplace=True)
developing_scrapped.rename(columns={'jobs':'jobs created'}, inplace=True)

In [8]:
#Concatinate all 19 dataframes column wise
developing = pd.concat([benin, developing_downloaded, developing_scrapped, ghana, ivory_coast, kenya_03_14, kenya_14_20, mali, mozambique, nigeria, rwanda, SA_03_08, SA_09_11, SA_12_14, SA_15_17, SA_18_20, sierra_leone, tanzania, uganda], axis=0)
developing.reset_index(drop=True, inplace=True)
developing.shape

(51444, 61)

In [20]:
#Get column names as sorted by the number of missing values
missing_values = developing.isna().sum().sort_values(ascending=False)
#reverse a list
missing_values = list(missing_values.index)[::-1]

In [23]:
developing

,project date,cluster,sector,destination country,activity,source country,jobs created,sub sector,source state,capital investment,...,position 3,telephone 1,joint venture companies,email 2,telephone 2,contact name,email 3,telephone 3,aj comment,aj source
0,43891,Financial Services,Financial services,Benin,Business Services,Cote d Ivoire,0.0,Corporate & investment banking,Lagunes,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,43831,Agribusiness,Food & Beverages,Benin,Manufacturing,United Kingdom,100.0,Fruits & vegetables & specialist foods,East Midlands (UK),0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,43831,Financial Services,Financial services,Benin,"Sales, Marketing & Support",Togo,0.0,Insurance,Togo,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43770,Financial Services,Financial services,Benin,Business Services,Mali,0.0,Retail banking,Bamako Capital District,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,43678,Transportation & Warehousing,Transportation & Warehousing,Benin,"Logistics, Distribution & Transportation",Germany,0.0,Air transportation,Nordrhein-Westfalen,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51439,37895,Transport Equipment,Automotive OEM,Uganda,Maintenance & Servicing,Japan,0.0,Automobiles,Chubu,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51440,37895,Professional Services,Business services,Uganda,Business Services,South Africa,0.0,Legal services,Gauteng,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51441,37834,"Wood, Apparel & Related Products","Paper, printing & packaging",Uganda,Manufacturing,China,114.0,"Pulp, paper, & paperboard",Not Specified,9.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51442,37742,Consumer Goods,Consumer electronics,Uganda,Manufacturing,Germany,0.0,Household appliances,Bayern,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51443,37742,ICT & Electronics,Communications,Uganda,ICT & Internet Infrastructure,Kuwait,0.0,Wireless telecommunication carriers,Al-Kuwait,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Display rows where email 1 is not null and email 2 is null
developing[developing['email 1 '].notnull()]

In [36]:
developing.to_csv('developing/developinger.csv', index=False)

In [14]:
#Get column names for each dataset
print("Benin\n",benin.columns)
print("Developing downloaded\n",developing_downloaded.columns)
print("Developing scrapped\n",developing_scrapped.columns)
print("Ghana\n",ghana.columns)
print("Ivory Coast\n",ivory_coast.columns)
print("Kenya 03-14\n",kenya_03_14.columns)
print("Kenya 14-20\n",kenya_14_20.columns)
print("Mali\n",mali.columns)
print("Mozambique\n",mozambique.columns)
print("Nigeria\n",nigeria.columns)
print("Rwanda\n",rwanda.columns)
print("SA 03-08\n",SA_03_08.columns)
print("SA 09-11\n",SA_09_11.columns)
print("SA 12-14\n",SA_12_14.columns)
print("SA 15-17\n",SA_15_17.columns)
print("SA 18-20\n",SA_18_20.columns)
print("Sierra Leone\n",sierra_leone.columns)
print("Tanzania\n",tanzania.columns)
print("Uganda\n",uganda.columns)

Benin
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Developing downloaded
 Index(['project date', 'year', 'month', 'day', 'source region',
       'source country', 'source state', 'source adm region', 'source city',
       'destination region', 'destination country', 'destination state',
       'destination adm region', 'destination city', 'free zone', 'relocation',
       'sector', 'sub sector', 'cluster', 'activity', 'jobs created',
       'estimated 20', 'capital investment', 'estimated 22', 'project type',
       'project status'],
      dtype='object')
Developing scrapped
 Index(['project date', 'parent company', 'investing company', 'source country',
       'relocation', 'destination country', 'free zone', 'sector',
       'sub sector', 'cluster', 'activity', 'capex', 'jobs created', 'type'],
      dtype='object')
Ghana
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
Ivory Coast
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
Kenya 03-14
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Kenya 14-20
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Mali
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Mozambique
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
Nigeria
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
Rwanda
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
SA 03-08
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
SA 09-11
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
SA 12-14
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
SA 15-17
 Index(['project date', 'investing company', 'website', 'source country',
       'source state', 'source admin region', 'source city',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'cluster',
       'activity', 'jobs created', 'estimated', 'capital investment',
       'estimated 1', 'source', 'contact name 1 ', 'position 1 ', 'email 1 ',
       'telephone 1 ', 'contact name 2 ', 'position 2 ', 'email 2 ',
       'telephone 2 ', 'contact name 3 ', 'position 3 ', 'email 3 ',
       'telephone 3 '],
      dtype='object')
SA 18-20
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Sierra Leone
 Index(['project date', 'investing company', 'aj comment', 'aj source',
       'website', 'source country', 'source state', 'source admin region',
       'source city', 'destination country', 'destination state',
       'destination admin region', 'destination city', 'free zone',
       'relocation', 'sector', 'cluster', 'activity', 'jobs created',
       'estimated', 'capital investment', 'estimated 1', 'source',
       'contact name'],
      dtype='object')
Tanzania
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')
Uganda
 Index(['project date', 'investing company', 'parent company',
       'company profile', 'website', 'revenue usd m ', 'headcount',
       'r d expenditure usd m ', 'year established', 'company email',
       'company telephone', 'source region', 'source country', 'source state',
       'source admin region', 'source city', 'destination region',
       'destination country', 'destination state', 'destination admin region',
       'destination city', 'free zone', 'relocation', 'sector', 'sub sector',
       'cluster', 'activity', 'jobs created', 'estimated',
       'capital investment', 'estimated 1', 'project type', 'project status',
       'motive description', 'markets served', 'joint venture companies',
       'source', 'contact name 1 ', 'position 1 ', 'email 1 ', 'telephone 1 ',
       'contact name 2 ', 'position 2 ', 'email 2 ', 'telephone 2 ',
       'contact name 3 ', 'position 3 ', 'email 3 ', 'telephone 3 '],
      dtype='object')