In [1]:
#Import python libraries
import pandas as pd
import numpy as np
import os

OG 2003 Update

In [2]:
#Import excel sheets from Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx
OG_2003_Update = pd.read_excel(r'Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx', sheet_name = 'OG 2003 Update', header = 0,engine="openpyxl",usecols="A:Z")

In [3]:
#Drop rows where value in num is not an integer & reset index
OG_2003_Update = OG_2003_Update[OG_2003_Update['num'].apply(lambda x: isinstance(x, int))]
OG_2003_Update = OG_2003_Update.reset_index(drop=True)

OG 2018 Downloaded

In [4]:
#Import excel sheets from Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx
OG_2018_Downloaded = pd.read_excel(r'Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx', sheet_name = 'OG 2018 Downloaded', header = 0,engine="openpyxl")

OG 2018 Scrapped

In [15]:
#Import excel sheets from Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx
OG_2018_Scrapped = pd.read_excel(r'Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx', sheet_name = 'OG 2018 Scrapped', header = 0,engine="openpyxl",usecols="A:O") 
#Remove Unnamed: 0 column
OG_2018_Scrapped = OG_2018_Scrapped.drop(columns=['Unnamed: 0'])

Data From2003

In [6]:
#Import excel sheets from Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx and only certain columns
Data_From2003 = pd.read_excel(r'Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx', sheet_name = 'Data From2003', header = 0,engine="openpyxl",usecols = "A:M")

Consolidated Africa FDI

In [7]:
#Import excel sheets from Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx
Consolidated_Africa_FDI = pd.read_excel(r'Consolidated FDI Data/2003 - 2021 FDI Africa.xlsx', sheet_name = 'Consolidated Africa FDI', header = 0,engine="openpyxl")

In [16]:
#Print the shape of the dataframes
print(OG_2003_Update.shape)
print(OG_2018_Downloaded.shape)
print(OG_2018_Scrapped.shape)
print(Consolidated_Africa_FDI.shape)

#Sum of all rows of all dataframes
print(OG_2003_Update.shape[0] + OG_2018_Downloaded.shape[0] + OG_2018_Scrapped.shape[0] + Consolidated_Africa_FDI.shape[0])

(80716, 26)
(2147, 25)
(22893, 14)
(11427, 13)
117183

In [19]:
OG_2018_Downloaded.drop(columns=['destination_region.1'], inplace=True)
OG_2003_Update.drop(columns=['dest_country.1'], inplace=True)

In [39]:
# Rename sub-sector column to subsector
OG_2018_Downloaded.rename(columns={'sub-sector':'subsector'}, inplace=True)
OG_2003_Update.rename(columns={'dest_country':'destination_country'}, inplace=True)
OG_2003_Update.rename(columns={'dest_region':'destination_region'}, inplace=True)
OG_2003_Update.rename(columns={'dest_city':'destination_city'}, inplace=True)
OG_2003_Update.rename(columns={'dest_state':'destination_state'}, inplace=True)
Consolidated_Africa_FDI.rename(columns={'dest_country':'destination_country'}, inplace=True)
OG_2018_Scrapped.rename(columns={'Sector':'sector'}, inplace=True)
OG_2018_Downloaded.rename(columns={'Date':'date'}, inplace=True)
OG_2018_Scrapped.rename(columns={'Date':'date'}, inplace=True)
OG_2018_Scrapped.rename(columns={'jobs':'jobs_created'}, inplace=True)

In [40]:
#Print column names of all dataframes in ascending order
print(OG_2003_Update.columns.sort_values())
print(OG_2018_Downloaded.columns.sort_values())
print(OG_2018_Scrapped.columns.sort_values())
print(Consolidated_Africa_FDI.columns.sort_values())

Index(['Email', 'S', 'Telephone', 'admin_region', 'capex', 'cluster',
       'contact', 'date', 'destination_city', 'destination_country',
       'destination_state', 'estimated', 'industry_activity',
       'industry_sector', 'investing_company', 'jobs_created', 'motive', 'num',
       'parent_company', 'position', 'project_type', 'source_city',
       'source_country', 'source_state', 'subsector'],
      dtype='object')
Index(['Continent', 'activity', 'capital_investment', 'cluster', 'date',
       'destination_adm_region', 'destination_city', 'destination_country',
       'destination_region', 'destination_state', 'estimated...20',
       'estimated...22', 'free_zone', 'jobs_created', 'project_status',
       'project_type', 'relocation', 'sector', 'source_adm_region',
       'source_city', 'source_country', 'source_region', 'source_state',
       'subsector'],
      dtype='object')
Index(['Freezone', 'activity', 'capex', 'cluster', 'date',
       'destination_country', 'investing_company', 'jobs_created',
       'parent_company', 'relocation', 'sector', 'source_country', 'subsector',
       'type'],
      dtype='object')
Index(['Continent', 'capex', 'cluster', 'date', 'destination_country',
       'industry_activity', 'industry_sector', 'investing_company',
       'jobs_created', 'parent_company', 'project_type', 'source_country',
       'subsector'],
      dtype='object')

In [41]:
#Concatinate all dataframes column wise
Consolidated_Africa_FDI_combined = pd.concat([OG_2003_Update,OG_2018_Downloaded,OG_2018_Scrapped,Consolidated_Africa_FDI], axis = 0).reset_index(drop=True)

In [42]:
Consolidated_Africa_FDI_combined

,destination_country,num,date,investing_company,parent_company,source_country,source_state,source_city,destination_state,admin_region,...,free_zone,relocation,sector,activity,estimated...20,capital_investment,estimated...22,project_status,Freezone,type
0,Afghanistan,1,2018-02-01 00:00:00,Nestle,Nestle,Switzerland,Switzerland,Vevey,Kabul,Not Specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,2,2017-11-01 00:00:00,Neuron Technologies,Neuron Technologies,Azerbaijan,Azerbaijan,Baku,Kabul,Not Specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,3,2015-10-01 00:00:00,Aptech,Aptech,India,Maharashtra,Mumbai,Kabul,Not Specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,4,2013-12-01 00:00:00,Telecom Development Company Afghanistan (Roshan),Aga Khan Development Network (AKDN),Switzerland,Switzerland,Geneva,Kabul,Not Specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,5,2013-08-01 00:00:00,Logenix,Logenix,United States,Virginia,Alexandria (VA),Kabul,Not Specified,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117178,Ethiopia,NaN,2021-02-01 00:00:00,Orange France Telecom,Orange France Telecom,France,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117179,South Africa,NaN,2021-02-01 00:00:00,Pagero,Pagero,Sweden,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117180,South Africa,NaN,2021-02-01 00:00:00,The MCG Group,The MCG Group,United Kingdom,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117181,Kenya,NaN,2021-02-01 00:00:00,AFR IX Telecom,Zunder Systems,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117182,Zambia,NaN,2021-02-01 00:00:00,AFR IX Telecom,Zunder Systems,Spain,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
Consolidated_Africa_FDI_combined.to_csv('Consolidated FDI Data/Consolidated_Africa_FDI_combined.csv', index=False)