In [1]:
import numpy as np
import pandas as pd

In [2]:
# all available mine categories in SPG dataset
string='Antimony, Bauxite, Beryllium, Bismuth, Cerium, Chromite, Chromium, Cobalt, Copper, Dysprosium, Gallium, Germanium, Graphite, Heavy Mineral Sands, Ilmenite, Indium, Iron Ore, Lanthanides, Lanthanum, Lead, Leucoxene, Lithium, Magnesium, Manganese, Molybdenum, Neodymium, Nickel, Niobium, Phosphate, Potash, Praseodymium, Rutile, Samarium, Scandium, Selenium, Tantalum, Tellurium, Tin, Titanium, Tungsten, Vanadium, Ytterbium, Yttrium, Zinc, Zircon'
ls=string.split(', ')
print(len(ls))

45

In [3]:
def process(path, property_type):
    tmp = pd.read_csv(path)
    print(tmp.shape)
    tmp = tmp.drop([0,2,3], axis=0)
    tmp = tmp.drop(tmp.columns[[2,18]],axis=1)
    tmp.head()
    df = tmp.iloc[1:,:]
    df.columns = tmp.iloc[0]
    df['CONTAINED_R_AND_R_PCT_TONNE'] = df['CONTAINED_R_AND_R_PCT_TONNE'].replace(np.nan, 0)
    df['property_type']= property_type
    df['Unit']= 'Tonnes'

    return df

In [4]:
def primary_commodity_reserve(PRIMARY_COMMODITY,Antimony, Bauxite, Beryllium, Bismuth, Cerium, Chromite, Chromium, Cobalt, Copper, Dysprosium, Gallium, Germanium, Graphite, Heavy_Mineral_Sands, Ilmenite, Indium, Iron_Ore, Lanthanides, Lanthanum, Lead, Leucoxene, Lithium, Magnesium, Manganese, Molybdenum, Neodymium, Nickel, Niobium, Phosphate, Potash, Praseodymium, Rutile, Samarium, Scandium, Selenium, Tantalum, Tellurium, Tin, Titanium, Tungsten, Vanadium, Ytterbium, Yttrium, Zinc, Zircon):
    commodity_ls=[]
    ls_2= list((Antimony, Bauxite, Beryllium, Bismuth, Cerium, Chromite, Chromium, Cobalt, Copper, Dysprosium, Gallium, Germanium, Graphite, Heavy_Mineral_Sands, Ilmenite, Indium, Iron_Ore, Lanthanides, Lanthanum, Lead, Leucoxene, Lithium, Magnesium, Manganese, Molybdenum, Neodymium, Nickel, Niobium, Phosphate, Potash, Praseodymium, Rutile, Samarium, Scandium, Selenium, Tantalum, Tellurium, Tin, Titanium, Tungsten, Vanadium, Ytterbium, Yttrium, Zinc, Zircon))
    for j in PRIMARY_COMMODITY.split(','):
        for i in range(len(ls)):
            if j == ls[i]:
                commodity_ls.append(ls_2[i])
    if commodity_ls == [] or commodity_ls ==[0]:
        commodity_ls = np.nan
    return commodity_ls

### Download data from 'Screener'
because excel plug-in cannot get 'property type' information, data are download from Screener in web production using 'all_field_2' stored field table

In [5]:
project_1= process('./input/project_1.csv', 'project')
project_2= process('./input/project_2.csv', 'project')
project_3= process('./input/project_3.csv', 'project')
project_4= process('./input/project_4.csv', 'project')
project_5= process('./input/project_5.csv', 'project')
project_6= process('./input/project_6.csv', 'project')

smelter = process('./input/smelter.csv', 'smelter')
refinery = process('./input/refinery.csv', 'refinery')
pellet_plant = process('./input/pellet_plant.csv', 'pellet_plant')
concentrator = process('./input/concentrator.csv', 'concentrator')
coal_washing_plant = process('./input/coal_washing_plant.csv', 'project')
plant = process('./input/plant.csv', 'project')

(4985, 64)

C:\Users\Xiaoyi WU\AppData\Local\Temp\ipykernel_26528\449374409.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CONTAINED_R_AND_R_PCT_TONNE'] = df['CONTAINED_R_AND_R_PCT_TONNE'].replace(np.nan, 0)
C:\Users\Xiaoyi WU\AppData\Local\Temp\ipykernel_26528\449374409.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['property_type']= property_type
C:\Users\Xiaoyi WU\AppData\Local\Temp\ipykernel_26528\449374409.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Unit']= 'Tonnes'

(7419, 64)
(5920, 64)
(7248, 64)
(4126, 64)
(7047, 64)
(1145, 64)
(1115, 64)
(73, 64)
(46, 64)
(65, 64)
(415, 64)

In [6]:
data_process = pd.concat([
                          project_1, project_2,project_3,
                          project_4, 
                          project_5,
                          project_6,
                          smelter,refinery,pellet_plant, concentrator, coal_washing_plant, plant
                         ],axis=0, keys = project_1.columns,ignore_index = True)
data_process.head()

1,PROP_NAME,PROP_ID,ALSO_KNOWN_AS,OWNER_LIST,OWNER_PCT,DEV_STAGE,ACTV_STATUS,COMMODITIES_LIST,PRIMARY_COMMODITY,R_AND_R_ORE_TONNAGE,...,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,property_type,Unit
0,11 RAU-Novaya,68289,NaN,Sodeistvie Private Enterprise (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
1,12 Mile Creek,66178,NaN,U&D Coal Limited (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
2,14 Karats,65525,NaN,Dios Exploration Inc. (Owner) 100%,100.00,Grassroots,Inactive,"Gold,Diamonds",Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
3,14 Mile Well Extension,63665,NaN,Private Interest (Owner) 100%,100.00,Grassroots,Inactive,Gold,Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
4,15 Mile Silver City,65760,NaN,North Lily Mining Company (Owner) 50%,50.00,Grassroots,Inactive,"Gold,Silver",Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes

In [7]:
data_process.head()

1,PROP_NAME,PROP_ID,ALSO_KNOWN_AS,OWNER_LIST,OWNER_PCT,DEV_STAGE,ACTV_STATUS,COMMODITIES_LIST,PRIMARY_COMMODITY,R_AND_R_ORE_TONNAGE,...,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,CONTAINED_R_AND_R_PCT_TONNE,property_type,Unit
0,11 RAU-Novaya,68289,NaN,Sodeistvie Private Enterprise (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
1,12 Mile Creek,66178,NaN,U&D Coal Limited (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
2,14 Karats,65525,NaN,Dios Exploration Inc. (Owner) 100%,100.00,Grassroots,Inactive,"Gold,Diamonds",Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
3,14 Mile Well Extension,63665,NaN,Private Interest (Owner) 100%,100.00,Grassroots,Inactive,Gold,Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes
4,15 Mile Silver City,65760,NaN,North Lily Mining Company (Owner) 50%,50.00,Grassroots,Inactive,"Gold,Silver",Gold,NaN,...,0,0,0,0,0,0,0,0,project,Tonnes

In [8]:
def primary_commodity_reserve(PRIMARY_COMMODITY,Antimony, Bauxite, Beryllium, Bismuth, Cerium, Chromite, Chromium, Cobalt, Copper, Dysprosium, Gallium, Germanium, Graphite, Heavy_Mineral_Sands, Ilmenite, Indium, Iron_Ore, Lanthanides, Lanthanum, Lead, Leucoxene, Lithium, Magnesium, Manganese, Molybdenum, Neodymium, Nickel, Niobium, Phosphate, Potash, Praseodymium, Rutile, Samarium, Scandium, Selenium, Tantalum, Tellurium, Tin, Titanium, Tungsten, Vanadium, Ytterbium, Yttrium, Zinc, Zircon):
    commodity_ls=[]
    ls_2= list((Antimony, Bauxite, Beryllium, Bismuth, Cerium, Chromite, Chromium, Cobalt, Copper, Dysprosium, Gallium, Germanium, Graphite, Heavy_Mineral_Sands, Ilmenite, Indium, Iron_Ore, Lanthanides, Lanthanum, Lead, Leucoxene, Lithium, Magnesium, Manganese, Molybdenum, Neodymium, Nickel, Niobium, Phosphate, Potash, Praseodymium, Rutile, Samarium, Scandium, Selenium, Tantalum, Tellurium, Tin, Titanium, Tungsten, Vanadium, Ytterbium, Yttrium, Zinc, Zircon))
    for j in PRIMARY_COMMODITY.split(','):
        for i in range(len(ls)):
            if j == ls[i]:
                commodity_ls.append(ls_2[i])
    if commodity_ls == [] or commodity_ls ==[0]:
        commodity_ls = np.nan
    return commodity_ls

In [9]:
data_process['primary_commodity_reserve_and_resource']=data_process[['PRIMARY_COMMODITY','CONTAINED_R_AND_R_PCT_TONNE']].apply(lambda x: primary_commodity_reserve(*x),axis=1)

In [10]:
print(data_process.shape)
data_drop = data_process.drop(["CONTAINED_R_AND_R_PCT_TONNE"], axis=1)
print(data_drop.shape)
data_drop.columns

(39556, 65)
(39556, 20)

Index(['PROP_NAME', 'PROP_ID', 'ALSO_KNOWN_AS', 'OWNER_LIST', 'OWNER_PCT',
       'DEV_STAGE', 'ACTV_STATUS', 'COMMODITIES_LIST', 'PRIMARY_COMMODITY',
       'R_AND_R_ORE_TONNAGE', 'R_AND_R_AS_OF', 'COUNTRY_NAME',
       'STATE_PROVINCE', 'GENERAL_COMMENTS', 'LATITUDE', 'LONGITUDE',
       'IN_SITU_VALUE_R_AND_R_TONNAGE', 'property_type', 'Unit',
       'primary_commodity_reserve_and_resource'],
      dtype='object', name=1)

In [11]:
data_drop

1,PROP_NAME,PROP_ID,ALSO_KNOWN_AS,OWNER_LIST,OWNER_PCT,DEV_STAGE,ACTV_STATUS,COMMODITIES_LIST,PRIMARY_COMMODITY,R_AND_R_ORE_TONNAGE,R_AND_R_AS_OF,COUNTRY_NAME,STATE_PROVINCE,GENERAL_COMMENTS,LATITUDE,LONGITUDE,IN_SITU_VALUE_R_AND_R_TONNAGE,property_type,Unit,primary_commodity_reserve_and_resource
0,11 RAU-Novaya,68289,NaN,Sodeistvie Private Enterprise (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,NaN,Ukraine,Luhans'ka Oblast',NaN,48.519540,38.658270,NaN,project,Tonnes,NaN
1,12 Mile Creek,66178,NaN,U&D Coal Limited (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,NaN,Australia,Queensland,"As at 2017, U&D still held ownership at 12 Mil...",(23.163000),149.083000,NaN,project,Tonnes,NaN
2,14 Karats,65525,NaN,Dios Exploration Inc. (Owner) 100%,100.00,Grassroots,Inactive,"Gold,Diamonds",Gold,NaN,NaN,Canada,Quebec,NaN,52.728000,(71.490000),NaN,project,Tonnes,NaN
3,14 Mile Well Extension,63665,NaN,Private Interest (Owner) 100%,100.00,Grassroots,Inactive,Gold,Gold,NaN,NaN,Australia,Western Australia,NaN,(28.937860),122.006770,NaN,project,Tonnes,NaN
4,15 Mile Silver City,65760,NaN,North Lily Mining Company (Owner) 50%,50.00,Grassroots,Inactive,"Gold,Silver",Gold,NaN,NaN,Canada,Yukon Territory,NaN,64.307900,(139.910020),NaN,project,Tonnes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39551,Yuromayo Plant,62906,NaN,Gold Horizons Mining Co Ltd. (Owner) 100%,100.00,Operating,Active,Gold,Gold,NaN,NaN,Peru,Arequipa,"(Dec 1, 2014) Annual Report 2013: Operations f...",(16.423170),(71.928910),NaN,project,Tonnes,NaN
39552,Zhejiang Plant,61944,Tongxiang,"Zhejiang Huayou Cobalt Co., Ltd (Owner) 100%",100.00,Operating,Active,"Nickel,Cobalt",Nickel,NaN,NaN,China,Zhejiang,"As of September 2020, the capacity at the Zhej...",30.136520,120.868650,NaN,project,Tonnes,NaN
39553,Zhongjian Jinma Plant,82901,NaN,NaN,NaN,NaN,Active,Nickel,Nickel,NaN,NaN,China,Nei Mongol,NaN,41.534280,113.582350,NaN,project,Tonnes,NaN
39554,Zhuzhou Plant,86402,"Changsha, Hunan",Hunan Nonferrous Metals Corporation Limited (O...,31.44,Closed,Inactive,"Zinc,Lead",Zinc,NaN,NaN,China,Hunan,"In 2019, old zinc smelter was permanently clos...",27.842210,113.232290,NaN,project,Tonnes,NaN
39555,Zimalloys Plant,65049,NaN,Benscore Investments (Private) Limited (Owner)...,100.00,Operating,Active,Ferrochrome,Ferrochrome,NaN,NaN,Zimbabwe,Midlands,NaN,(19.457580),29.794600,NaN,project,Tonnes,NaN

In [12]:
output_data=data_drop.rename(columns={
    "PROP_NAME": "Property name", "OWNER_LIST": "OWNER(S)", "OWNER_PCT":"Equity ownership %",
    "DEV_STAGE":"DEVELOPMENT STAGE", "ACTV_STATUS": "ACTIVITY STATUS", "COMMODITIES_LIST":"COMMODITY(S)", 
    "PRIMARY_COMMODITY": "PRIMARY COMMODITY", "R_AND_R_ORE_TONNAGE":"TOTAL RESERVES AND RESOURCES(tonnage)","primary_commodity_reserve_and_resource":"PRIMARY RESERVES AND RESOURCES(tonnage)", "IN_SITU_VALUE_R_AND_R_TONNAGE":"TOTAL IN-SITU VALUE ($M)",
    "R_AND_R_AS_OF": "RESERVES & RESOURCES AS OF DATE", "ALSO_KNOWN_AS":"Also Known As", "PROP_ID":"Property ID", 
    "property_type": "Property type", "COUNTRY_NAME":"Country/Region", "STATE_PROVINCE":"State or Province",
    "GENERAL_COMMENTS" :"Comments"
}, errors="raise")
output_data.head()

1,Property name,Property ID,Also Known As,OWNER(S),Equity ownership %,DEVELOPMENT STAGE,ACTIVITY STATUS,COMMODITY(S),PRIMARY COMMODITY,TOTAL RESERVES AND RESOURCES(tonnage),RESERVES & RESOURCES AS OF DATE,Country/Region,State or Province,Comments,LATITUDE,LONGITUDE,TOTAL IN-SITU VALUE ($M),Property type,Unit,PRIMARY RESERVES AND RESOURCES(tonnage)
0,11 RAU-Novaya,68289,NaN,Sodeistvie Private Enterprise (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,NaN,Ukraine,Luhans'ka Oblast',NaN,48.519540,38.658270,NaN,project,Tonnes,NaN
1,12 Mile Creek,66178,NaN,U&D Coal Limited (Owner) 100%,100.00,Grassroots,Inactive,Coal,Coal,NaN,NaN,Australia,Queensland,"As at 2017, U&D still held ownership at 12 Mil...",(23.163000),149.083000,NaN,project,Tonnes,NaN
2,14 Karats,65525,NaN,Dios Exploration Inc. (Owner) 100%,100.00,Grassroots,Inactive,"Gold,Diamonds",Gold,NaN,NaN,Canada,Quebec,NaN,52.728000,(71.490000),NaN,project,Tonnes,NaN
3,14 Mile Well Extension,63665,NaN,Private Interest (Owner) 100%,100.00,Grassroots,Inactive,Gold,Gold,NaN,NaN,Australia,Western Australia,NaN,(28.937860),122.006770,NaN,project,Tonnes,NaN
4,15 Mile Silver City,65760,NaN,North Lily Mining Company (Owner) 50%,50.00,Grassroots,Inactive,"Gold,Silver",Gold,NaN,NaN,Canada,Yukon Territory,NaN,64.307900,(139.910020),NaN,project,Tonnes,NaN

In [13]:
output_data.to_csv('final_data.csv')

### Validation

In [14]:
template = pd.read_csv('./input/SNL dataset.csv')
print(template.shape)
template

(1, 19)

,PROPERTY,OWNER(S),Equity ownership %,DEVELOPMENT STAGE,ACTIVITY STATUS,COMMODITY(S),PRIMARY COMMODITY,PRIMARY RESERVES AND RESOURCES,UNIT,TOTAL IN-SITU VALUE ($M)¹,RESERVES & RESOURCES AS OF DATE²,Property ID,Also Known As,Property type,Country/Region,State or Province,Comments,Latitude,Longitude
0,Morro Dos Seis Lagos,"CPRM, Companhia Brasileira de Metalu",NA (NOTE _ not sure the best way to contruct t...,Reserves Development,Inactive,"Niobium, Lanthanides",Niobium,"81,421,631",Tonnes,"2,849,757.10",5/31/2011,37090,"Sao Gabriel da Cachoeira, Seis Lagos",Project,Brazil,Amazonas,Seis Lagos hosted measured resources of 38.4 m...,0.28333,66.68333

In [15]:
# have one more variable compared to template: TOTAL RESERVES AND RESOURCES(tonnage)
print(output_data.shape)
output_data.loc[output_data['Property ID']=='37090']

(39556, 20)

1,Property name,Property ID,Also Known As,OWNER(S),Equity ownership %,DEVELOPMENT STAGE,ACTIVITY STATUS,COMMODITY(S),PRIMARY COMMODITY,TOTAL RESERVES AND RESOURCES(tonnage),RESERVES & RESOURCES AS OF DATE,Country/Region,State or Province,Comments,LATITUDE,LONGITUDE,TOTAL IN-SITU VALUE ($M),Property type,Unit,PRIMARY RESERVES AND RESOURCES(tonnage)
22564,Morro Dos Seis Lagos,37090,"Sao Gabriel da Cachoeira, Seis Lagos",Companhia Brasileira de Metalurgia e Mineração...,NaN,Reserves Development,Inactive,"Niobium,Lanthanides",Niobium,"2,897,908,800",5/31/2011,Brazil,Amazonas,Seis Lagos hosted measured resources of 38.4 m...,0.283330,(66.683330),"2,849,757.1",project,Tonnes,"[81,421,631]"